// Auto-regenerator for src/libs/og/og-mesh-data.ts.
// One-shot dev script. Run with: node scripts/precompute-og-mesh.mjs
//
// Generates a level-2 subdivided icosphere, applies a fixed camera rotation,
// orthographically projects to a 720x600 viewbox, back-face culls, and emits
// a deduped edge list as a TypeScript module. Run once locally and commit
// the output. NOT part of the build pipeline.

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUTPUT = join(__dirname, '..', 'src', 'libs', 'og', 'og-mesh-data.ts')

const PHI = (1 + Math.sqrt(5)) / 2

const baseVertices = [
  [-1, PHI, 0],
  [1, PHI, 0],
  [-1, -PHI, 0],
  [1, -PHI, 0],
  [0, -1, PHI],
  [0, 1, PHI],
  [0, -1, -PHI],
  [0, 1, -PHI],
  [PHI, 0, -1],
  [PHI, 0, 1],
  [-PHI, 0, -1],
  [-PHI, 0, 1]
].map(normalize)

const baseFaces = [
  [0, 11, 5],
  [0, 5, 1],
  [0, 1, 7],
  [0, 7, 10],
  [0, 10, 11],
  [1, 5, 9],
  [5, 11, 4],
  [11, 10, 2],
  [10, 7, 6],
  [7, 1, 8],
  [3, 9, 4],
  [3, 4, 2],
  [3, 2, 6],
  [3, 6, 8],
  [3, 8, 9],
  [4, 9, 5],
  [2, 4, 11],
  [6, 2, 10],
  [8, 6, 7],
  [9, 8, 1]
]

function normalize([x, y, z]) {
  const len = Math.hypot(x, y, z)
  return [x / len, y / len, z / len]
}

function midpoint(a, b) {
  return normalize([(a[0] + b[0]) / 2, (a[1] + b[1]) / 2, (a[2] + b[2]) / 2])
}

function subdivide(vertices, faces) {
  const newVertices = [...vertices]
  const newFaces = []
  const cache = new Map()

  function getMid(i, j) {
    const key = i < j ? `${i}-${j}` : `${j}-${i}`
    if (cache.has(key)) return cache.get(key)
    const idx = newVertices.length
    newVertices.push(midpoint(newVertices[i], newVertices[j]))
    cache.set(key, idx)
    return idx
  }

  for (const [a, b, c] of faces) {
    const ab = getMid(a, b)
    const bc = getMid(b, c)
    const ca = getMid(c, a)
    newFaces.push([a, ab, ca], [b, bc, ab], [c, ca, bc], [ab, bc, ca])
  }

  return { vertices: newVertices, faces: newFaces }
}

let mesh = { vertices: baseVertices, faces: baseFaces }
mesh = subdivide(mesh.vertices, mesh.faces)
mesh = subdivide(mesh.vertices, mesh.faces)

const rotY = (25 * Math.PI) / 180
const rotX = (15 * Math.PI) / 180
const cosY = Math.cos(rotY),
  sinY = Math.sin(rotY)
const cosX = Math.cos(rotX),
  sinX = Math.sin(rotX)

function rotate([x, y, z]) {
  const x1 = x * cosY + z * sinY
  const z1 = -x * sinY + z * cosY
  const y2 = y * cosX - z1 * sinX
  const z2 = y * sinX + z1 * cosX
  return [x1, y2, z2]
}

const rotated = mesh.vertices.map(rotate)

const VIEW = { width: 720, height: 600 }
const cx = VIEW.width / 2
const cy = VIEW.height / 2
const radius = 240

function project([x, y, _z]) {
  return [cx + x * radius, cy - y * radius]
}

const projected = rotated.map(project)

function faceNormal([ax, ay, az], [bx, by, bz], [cx, cy, cz]) {
  const ux = bx - ax,
    uy = by - ay,
    uz = bz - az
  const vx = cx - ax,
    vy = cy - ay,
    vz = cz - az
  return [uy * vz - uz * vy, uz * vx - ux * vz, ux * vy - uy * vx]
}

const edgeSet = new Set()
const edges = []

for (const [a, b, c] of mesh.faces) {
  const n = faceNormal(rotated[a], rotated[b], rotated[c])
  if (n[2] <= 0) continue

  for (const [i, j] of [
    [a, b],
    [b, c],
    [c, a]
  ]) {
    const key = i < j ? `${i}-${j}` : `${j}-${i}`
    if (edgeSet.has(key)) continue
    edgeSet.add(key)
    const [x1, y1] = projected[i]
    const [x2, y2] = projected[j]
    edges.push([round(x1), round(y1), round(x2), round(y2)])
  }
}

function round(n) {
  return Math.round(n * 100) / 100
}

const lines = edges.map(([x1, y1, x2, y2]) => `  [${x1}, ${y1}, ${x2}, ${y2}]`)

const content = `// Auto-generated by scripts/precompute-og-mesh.mjs.
// DO NOT EDIT by hand — re-run the script to regenerate.
//
// Level-2 icosphere wireframe, ortho-projected to a 720x600 viewbox after a
// fixed Y/X camera rotation. Back-face culled at compute time so the runtime
// only iterates visible edges (server-only, never imported by client code).

// server-only

export const MESH_VIEWBOX = { width: ${VIEW.width}, height: ${VIEW.height} } as const

export const MESH_EDGES: ReadonlyArray<readonly [number, number, number, number]> = [
${lines.join(',\n')}
]

export const MESH_EDGE_COUNT = ${edges.length}
`

writeFileSync(OUTPUT, content, 'utf8')
console.log(`Wrote ${edges.length} edges to ${OUTPUT}`)
