// Validates the generated sitemap at public/sitemap.xml. Exits 1 on any failure.
//
// The sitemap is generated by next-sitemap during `yarn build`. If that step is
// skipped, /sitemap.xml falls through to the Next.js HTML 404 page and every
// XML client (browsers, Search Console, crawlers) reports a parse error instead
// of a missing file. Yarn does not run npm-style pre/post lifecycle scripts, so
// the generation step must stay chained explicitly inside `build` — this check
// is what proves it is still wired up.
//
// Run after `yarn build`. Override the file with --file=<path>.

const fs = require('fs')
const path = require('path')
const { Window } = require('happy-dom')

const argFile = (process.argv.find((a) => a.startsWith('--file=')) || '').replace('--file=', '')
const sitemapFile = argFile || path.join(process.cwd(), 'public', 'sitemap.xml')
const robotsFile = path.join(process.cwd(), 'public', 'robots.txt')
const rel = (p) => path.relative(process.cwd(), p).replace(/\\/g, '/')

const errors = []
const fail = (msg) => errors.push(msg)

function report() {
  if (errors.length === 0) return
  console.error(`[validate-sitemap] FAIL — ${errors.length} error(s) in ${rel(sitemapFile)}`)
  for (const e of errors) console.error(`  - ${e}`)
  process.exit(1)
}

if (!fs.existsSync(sitemapFile)) {
  fail(`${rel(sitemapFile)} does not exist — next-sitemap did not run during the build.`)
  fail('Check that `build` in package.json still chains the sitemap generation step.')
  report()
}

const xml = fs.readFileSync(sitemapFile, 'utf8').trim()

if (!xml) fail('File is empty.')
if (/^<!DOCTYPE html/i.test(xml) || /<html[\s>]/i.test(xml)) {
  fail('File is HTML, not XML — a 404 page or error page was written in place of the sitemap.')
}
report()

// happy-dom's parser silently repairs bare ampersands, so scan for them directly.
// A raw `&` is the failure mode when a URL with query params reaches <image:loc>,
// which next-sitemap writes without escaping.
const unescaped = [...xml.matchAll(/&(?!(?:amp|lt|gt|quot|apos|#\d+|#x[0-9a-fA-F]+);)/g)]
for (const m of unescaped.slice(0, 5)) {
  fail(`Unescaped '&' at offset ${m.index}: ...${xml.slice(Math.max(0, m.index - 50), m.index + 30)}...`)
}
if (unescaped.length > 5) fail(`...and ${unescaped.length - 5} more unescaped '&'.`)

const doc = new new Window().DOMParser().parseFromString(xml, 'text/xml')
const parserErrors = doc.getElementsByTagName('parsererror')
if (parserErrors.length > 0) fail(`Malformed XML: ${parserErrors[0].textContent.trim().split('\n')[0]}`)
report()

const root = doc.documentElement
if (!root || root.tagName.toLowerCase() !== 'urlset') {
  fail(`Root element is <${root ? root.tagName : 'none'}>, expected <urlset>.`)
  report()
}

const urls = [...doc.getElementsByTagName('url')]
if (urls.length === 0) fail('No <url> entries — the sitemap is structurally valid but empty.')

const seen = new Set()
const origins = new Set()

function checkLoc(raw, label) {
  if (!raw) return fail(`${label} is empty.`)
  let parsed
  try {
    parsed = new URL(raw)
  } catch {
    return fail(`${label} is not an absolute URL: ${raw}`)
  }
  if (parsed.protocol !== 'https:') fail(`${label} is not https: ${raw}`)
  return parsed
}

for (const url of urls) {
  const locEl = [...url.children].find((c) => c.tagName.toLowerCase() === 'loc')
  const loc = locEl && locEl.textContent.trim()
  const parsed = checkLoc(loc, '<loc>')
  if (!parsed) continue
  origins.add(parsed.origin)
  if (seen.has(loc)) fail(`Duplicate <loc>: ${loc}`)
  seen.add(loc)
}

for (const el of doc.getElementsByTagName('image:loc')) {
  checkLoc(el.textContent.trim(), '<image:loc>')
}

if (origins.size > 1) fail(`Mixed origins in <loc> entries: ${[...origins].join(', ')}`)
if (origins.has('http://localhost:3000') || [...origins].some((o) => o.includes('localhost'))) {
  fail('Sitemap contains localhost URLs.')
}

// robots.txt is committed while the sitemap is generated, so the two drift
// independently. A Sitemap: line pointing at the wrong host is invisible until a
// crawler follows it.
if (fs.existsSync(robotsFile)) {
  const robots = fs.readFileSync(robotsFile, 'utf8')

  // /api/og renders every og:image. It sits under the broader `/api/` Disallow,
  // so it needs an explicit Allow carve-out (longest-match wins in Google/Bing).
  // Without it, Google silently reports each social card as "Blocked by
  // robots.txt" and skips it for rich results.
  if (!/^\s*Allow:\s*\/api\/og\s*$/im.test(robots)) {
    fail(`${rel(robotsFile)} is missing "Allow: /api/og". og:image URLs fall under the /api/ Disallow.`)
  }

  if (origins.size === 1) {
    const declared = [...robots.matchAll(/^\s*Sitemap:\s*(\S+)\s*$/gim)].map((m) => m[1])
    if (declared.length === 0) fail(`${rel(robotsFile)} declares no Sitemap: line.`)
    for (const entry of declared) {
      try {
        if (new URL(entry).origin !== [...origins][0]) {
          fail(`${rel(robotsFile)} points at ${entry}, but the sitemap uses ${[...origins][0]}.`)
        }
      } catch {
        fail(`${rel(robotsFile)} has an unparseable Sitemap: entry: ${entry}`)
      }
    }
  }
}

report()

const imageCount = doc.getElementsByTagName('image:loc').length
console.log(`[validate-sitemap] OK — ${urls.length} URLs, ${imageCount} images, origin ${[...origins][0]}`)
